# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mac to Windows
email: aaron@easy-designs.net
description: > # this means to ignore newlines until "baseurl:"
  Resources for folks making the swtich. Please contribute links!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mactowindows.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
error_mode: :strict
markdown: kramdown
sass:
    sass_dir: _source/scss
    style: compressed
gems:
  - jekyll-feed
  - jekyll-filter-by_tag
  - jekyll-generator-section_from_site_tags
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - LICENSE
  - package.json
  - node_modules
  - gulpfile.js
  - README.md
  - Rakefile

# Site Config
post_teaser_limit: 5

# Cloudinary
cloudinary: http://res.cloudinary.com/mactowindows/image/fetch/w_WIDTH,ar_16:9,c_lfill/

# GA
GA_tracker: UA-86076128-3